// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiwVJNyMhEnsVxynpaZ8cAmJ6OAEIlPD4',
    appId: '1:579475468572:web:3ca703b3c7079d74950ad9',
    messagingSenderId: '579475468572',
    projectId: 'fir-auth-bacdc',
    authDomain: 'fir-auth-bacdc.firebaseapp.com',
    storageBucket: 'fir-auth-bacdc.firebasestorage.app',
    measurementId: 'G-ZVH0V9ZHL9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAwy5IrvswywjGoExjHWV17m6Qa6yzBzM',
    appId: '1:579475468572:android:51f42ed2e7fc2cee950ad9',
    messagingSenderId: '579475468572',
    projectId: 'fir-auth-bacdc',
    storageBucket: 'fir-auth-bacdc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfjSbOc74wppCk5x5D39fLym_NJt3PzKY',
    appId: '1:579475468572:ios:0135e3782ab66bb1950ad9',
    messagingSenderId: '579475468572',
    projectId: 'fir-auth-bacdc',
    storageBucket: 'fir-auth-bacdc.firebasestorage.app',
    iosBundleId: 'com.example.day11',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfjSbOc74wppCk5x5D39fLym_NJt3PzKY',
    appId: '1:579475468572:ios:0135e3782ab66bb1950ad9',
    messagingSenderId: '579475468572',
    projectId: 'fir-auth-bacdc',
    storageBucket: 'fir-auth-bacdc.firebasestorage.app',
    iosBundleId: 'com.example.day11',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiwVJNyMhEnsVxynpaZ8cAmJ6OAEIlPD4',
    appId: '1:579475468572:web:df9bef91d2e8ce85950ad9',
    messagingSenderId: '579475468572',
    projectId: 'fir-auth-bacdc',
    authDomain: 'fir-auth-bacdc.firebaseapp.com',
    storageBucket: 'fir-auth-bacdc.firebasestorage.app',
    measurementId: 'G-4EJ3RY7M1Y',
  );
}
